steps:
- name: 'node:12.6.0-alpine'
  args: ['yarn', 'install']
- name: 'node:12.6.0-alpine'
  args: ['yarn', 'run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/PPPP/XXXX:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/github.com/PPPP/XXXX:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/DEPLOYMENT-NAME'
    - 'apitee-cosmoya-com=gcr.io/$PROJECT_ID/github.com/PPPP/XXXX:$SHORT_SHA'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
